server:
    port: 9091

logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    dubbo:
        application.name : webcenter
        registry.address : zookeeper://127.0.0.1:2181
        protocol.name : dubbo
        protocol.port : 20880
        scan : com.tydic.webcenter.persistence.service


# 更多数据源
#custom :
#    datasource:
#        names : ds1,ds2
#        ds1 :
#            driver-class-name : com.mysql.jdbc.Driver
#            url : jdbc:mysql://localhost:3306/test1?useUnicode=true&amp;charaterEncoding=utf-8
#            username : root
#            password : 123456
#
#        ds2 :
#            driver-class-name : com.mysql.jdbc.Driver
#            url : jdbc:mysql://localhost:3306/test2?useUnicode=true&amp;charaterEncoding=utf-8
#            username : root
#            password : 123456

## 下面为连接池的补充设置，应用到上面所有数据源中
## 初始化大小，最小，最大
#spring.datasource.initialSize=5
#spring.datasource.minIdle=5
#spring.datasource.maxActive=20
## 配置获取连接等待超时的时间
#spring.datasource.maxWait=60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#spring.datasource.timeBetweenEvictionRunsMillis=60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
## 打开PSCache，并且指定每个连接上PSCache的大小
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#spring.datasource.filters=stat,wall,log4j
## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
## 合并多个DruidDataSource的监控数据
##spring.datasource.useGlobalDataSourceStat=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true
#spring.http.encoding.force=true


#
## LOGGING
#logging:
#    level:
#       com.ibatis:DEBUG

